delete from s_service_task
delete from s_device_file
delete from s_daily_record
delete from s_elec_record
delete from s_equip_apply
delete from s_equip_audit
delete from s_equip_check
delete from s_equip_user
delete from s_fast_feedback
delete from s_fast_survey
delete from s_field_apply
delete from s_field_survey
delete from s_file_path
delete from s_machine_record
delete from s_mtain_confide
delete from s_safe_confide
delete from s_task_attach
delete from s_task_require
delete from s_opt_record